(function(){/*

SPF
(c) 2012-2014 Google, Inc.
License: MIT
*/
function l(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function m(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}function n(){return(new Date).getTime()}function ba(){};function ca(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function q(a,b){if(a.classList)return a.classList.contains(b);for(var c=ca(a),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return!1}function da(a,b){a.classList?a.classList.add(b):q(a,b)||(a.className+=" "+b)}function ea(a,b){if(a.classList)a.classList.remove(b);else{for(var c=ca(a),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ")}};function r(a,b){return t[a]=b}var t=window._spf_state||{};window._spf_state=t;function u(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function fa(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function ga(a,b){if(a.filter)return a.filter(b,void 0);var c=[];u(a,function(a,e,f){b.call(void 0,a,e,f)&&c.push(a)});return c}
function ha(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;u(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function v(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};var ia={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},w={};"config"in t||r("config",w);w=t.config;function ja(a,b){var c=b||document;return c.querySelectorAll?c.querySelectorAll(a):[]}function ka(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);c.removeChild(a)}}function la(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}
function ma(a,b,c){a=a||"";b=b||document;var d=b.createElement("iframe");d.id=a;d.src='javascript:""';d.style.display="none";c&&(d.onload=l(c,null,d));b.body.appendChild(d);return d};function na(a,b,c,d){var e=d||{},f=!1,h=0,k,g=new XMLHttpRequest;g.open(a,b,!0);g.timing={};var p=g.abort;g.abort=function(){clearTimeout(k);g.onreadystatechange=null;p.call(g)};g.onreadystatechange=function(){var a=g.timing;if(2==g.readyState){a.responseStart=a.responseStart||n();f=-1<(g.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked");if(!f){var a=g.getResponseHeader("X-Firefox-Spdy"),c=window.chrome&&chrome.loadTimes&&chrome.loadTimes(),c=c&&c.wasFetchedViaSpdy;f=!(!a&&
!c)}e.B&&e.B(g)}else 3==g.readyState?f&&e.m&&(a=g.responseText.substring(h),h=g.responseText.length,e.m(g,a)):4==g.readyState&&(a.responseEnd=a.responseEnd||n(),window.performance&&window.performance.getEntriesByName&&(g.resourceTiming=window.performance.getEntriesByName(b)[0]),f&&e.m&&g.responseText.length>h&&(a=g.responseText.substring(h),h=g.responseText.length,e.m(g,a)),clearTimeout(k),e.A&&e.A(g))};a="POST"==a;if(e.headers)for(var y in e.headers)g.setRequestHeader(y,e.headers[y]),"content-type"==
y.toLowerCase()&&(a=!1);a&&g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.D&&(k=setTimeout(function(){g.abort();e.C&&e.C(g)},e.D));g.timing.fetchStart=n();g.send(c);return g};function oa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var pa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function x(a){a=a.split("#");var b=1==a.length;return[a[0],b?"":"#",b?"":a.slice(1).join("#")]};function qa(a){var b=z();a in b&&delete b[a]}function ra(){var a=z(),b;for(b in a)sa(a[b])||delete a[b];a=z();b=parseInt(w["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e,f;for(f in a)a[f].count<d&&(e=f,d=a[f].count);delete a[e]}}function sa(a){if(!(a&&"data"in a))return!1;var b=a.life,b=isNaN(b)?Infinity:b;return n()-a.time<b}function ta(a){var b=parseInt(t["cache-counter"],10)||0;b++;r("cache-counter",b);a.count=b}
function z(a){return!a&&"cache-storage"in t?t["cache-storage"]:r("cache-storage",a||{})};function ua(a,b,c,d){var e=window.history.state;d&&e&&(b=b||e);va(!0,a,b,c)}function va(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=n();r("history-timestamp",e);c["spf-timestamp"]=e;if(a)wa(c,b);else if(a=xa().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");r("history-url",b);d&&(d=t["history-callback"])&&d(b,c)}}
function ya(a){var b=window.location.href;if(t["history-ignore-pop"])r("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==t["history-url"]?(r("history-timestamp",c),wa(a,b)):(a["spf-back"]=c<parseInt(t["history-timestamp"],10),a["spf-current"]=t["history-url"],r("history-timestamp",c),r("history-url",b),(c=t["history-callback"])&&c(b,a))}}
function wa(a,b){var c=xa().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function xa(){var a=document.getElementById("history-iframe");a||(a=ma("history-iframe"));return a};function za(a,b){a&&b&&(a in A||(A[a]=[]),A[a].push(b))}function Aa(a,b){a in A&&b&&fa(A[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function Ba(a){a in A&&u(A[a],function(a,c,d){d[c]=null;a&&a()})}var A={};"ps-s"in t||r("ps-s",A);A=t["ps-s"];function B(a,b,c){var d=C[a];return a&&b?(d||(d=C[a]={items:[],l:0,i:0,p:1}),d.items.push({F:b,s:c||0})):d&&d.items.length||0}function D(a,b){var c=C[a];if(c){var d=!!c.l||!!c.i;0<c.p&&(b||!d)&&Ca(a,b)}}function E(a){(a=C[a])&&a.p--}function F(a,b){var c=C[a];c&&(c.p++,D(a,b))}function Da(a){var b=C[a];b&&(Ea(b),delete C[a])}function Fa(a){var b=parseInt(t.uid,10)||0;b++;return a["spf-key"]||(a["spf-key"]=""+r("uid",b))}
function Ca(a,b){var c=C[a];if(c&&(Ea(c),0<c.p&&c.items.length)){var d=c.items[0];if(d){var e=l(function(a,b){b();a()},null,l(Ca,null,a,b));b?(c.items.shift(),e(d.F)):Ga(c,d,e)}}}function Ga(a,b,c){b.s?(c=l(c,null,ba),a.i=setTimeout(c,b.s),b.s=0):(a.items.shift(),c=l(c,null,b.F),(b=(b=w["advanced-task-scheduler"])&&b.addTask)?a.l=b(c):a.i=setTimeout(c,0))}function Ea(a){if(a.l){var b=w["advanced-task-scheduler"];(b=b&&b.cancelTask)&&b(a.l);a.l=0}a.i&&(clearTimeout(a.i),a.i=0)}var C={};function G(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,J:b.J,I:b.I};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function H(a,b){var c=G(a);return b?c.href:x(c.href)[0]}
function Ha(a,b){var c=x(a);a=c[0];for(var d=0;d<b.length;d++)a=a.replace(new RegExp("([?&])"+b[d]+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(a,b){return"?"==b?b:""});oa(a,"?")&&(a=a.slice(0,-1));return a+c[1]+c[2]};function Ia(a,b,c,d){var e="js"==a;b=I(a,b);var f=c||"^"+b,h=J(a,f),k;c&&(k=K(a,c))&&b!=k&&(m(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:c,url:k}),e=k,Ja(a,c),e&&Ka(a,e),e=J(a,c),delete A[e],za(h,l(La,null,a,c,k)));e=J(a,b);if((e=L[e])&&f!=e){Ja(a,e);Ka(a,b);var g=J(a,e);g&&h&&g in A&&(A[h]=(A[h]||[]).concat(A[g]),delete A[g])}g=J(a,b);L[g]=f;Ma(a,f,b);za(h,d);d=l(Na,null,a);M(a,b)?(e&&f!=e&&(a=Oa(a,b))&&a.setAttribute("name",c||""),d()):(a=Pa(a,b,d,void 0,void 0,k))&&c&&a.setAttribute("name",
c)}function Qa(a,b){var c=K(a,b);Ja(a,b);c&&Ka(a,c);var d=J(a,b);delete A[d];La(a,b,c)}function La(a,b,c){c&&(m("js"==a?"spfjsunload":"spfcssunload",{name:b,url:c}),Ra(a,c))}function Na(a){var b=J(a,""),c;for(c in A)0==c.indexOf(b)&&fa(c.substring(b.length).split("|"),l(Sa,null,a))&&Ba(c)}
function Pa(a,b,c,d,e,f){function h(){M(a,b,e)&&Ta(2,a,b,e);k&&p&&p.parentNode&&g==document&&p.parentNode.removeChild(p);c&&setTimeout(c,0);return null}var k="js"==a;b=I(a,b);Ta(1,a,b,e);var g=d||document,p=g.createElement(k?"script":"link");if(!b)return h();var y=N(b);p.className=J(a,y);"onload"in p?p.onerror=p.onload=h:p.onreadystatechange=function(){/^c|loade/.test(p.readyState)&&h()};y=g.getElementsByTagName("head")[0];k?(p.async=!0,p.src=b,y.insertBefore(p,y.firstChild)):(p.rel="stylesheet",
p.href=b,(d=f&&Oa(a,f,d))?y.insertBefore(p,d):y.appendChild(p));return p}function Ra(a,b){b=I(a,b);var c=Oa(a,b,void 0);c&&c.parentNode&&c.parentNode.removeChild(c);c=J(a,b);delete O[c]}function Oa(a,b,c){b=N(b);a=J(a,b);return ja("."+a,c)[0]}function Ua(a){var b="js"==a,c=[];u(ja(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href,e=I(a,e);if(!M(a,e)){Ta(2,a,e);var f=N(e),f=J(a,f);da(d,f);if(f=d.getAttribute("name")){var h=J(a,e);L[h]=f;Ma(a,f,e)}c.push(d)}})}
function Va(a,b){if(b&&(b=I(a,b),!M(a,b))){var c=N(b),d=J(a,c),e=J(a,"prefetch"),c=document.getElementById(e);if(!c)c=ma(e,null,function(a){a.title=e;D(e,!0)});else if(c.contentWindow.document.getElementById(d))return;d=l(Wa,null,c,a,b,d,e);c.title?d():B(e,d)}}
function Wa(a,b,c,d,e){var f="css"==b;a=a.contentWindow.document;"js"==b?(b=a.createElement("object"),Xa?a.createElement("script").src=c:b.data=c,b.id=d,a.body.appendChild(b)):f?(b=Pa(b,c,null,a,e),b.id=d):(b=a.createElement("img"),b.src=c,b.id=d,a.body.appendChild(b))}
function Ya(a,b,c){for(var d="js"==a,e=K(a,c),f=b.replace(/\s/g,""),f=f||"",h=0,k=0,g=f.length;k<g;++k)h=31*h+f.charCodeAt(k),h%=4294967296;f="hash-"+h;Ma(a,c,f);!Za(a,f)&&(b=$a(a,b))&&(Ta(2,a,f),b&&!d&&(d=N(f),d=J(a,d),b.className=d,b.setAttribute("name",c)),(e=e&&e[0])&&Ra(a,e))}
function $a(a,b){b=pa(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body,d;"js"==a?(d=document.createElement("script"),d.text=b,c.appendChild(d),c.removeChild(d)):(d=document.createElement("style"),c.appendChild(d),"styleSheet"in d?d.styleSheet.cssText=b:d.appendChild(document.createTextNode(b)));return d}
function I(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=t[c]||"";if("[object String]"==Object.prototype.toString.call(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);b=0>b.indexOf("."+a)?b+"."+a:b;b=H(b)}else 0==d&&(b=H(b))}return b}function J(a,b,c){return a+"-"+b+(c?"-"+c:"")}function N(a){return a?String(a).replace(/[^\w]/g,""):""}function Ta(a,b,c,d){b=J(b,c,d);O[b]=a}function M(a,b,c){a=J(a,b,c);return O[a]}
function Za(a,b){var c=M(a,b);return""==b||2==c}function Ka(a,b){var c=J(a,b);delete L[c]}function Ma(a,b,c){a=J(a,b);P[a]=c}function K(a,b){var c=J(a,b);return P[c]}function Ja(a,b){var c=J(a,b);delete P[c]}function Sa(a,b){var c=K(a,b);return void 0!=c&&Za(a,c)}var O={},L={},P={},Xa=-1!=navigator.userAgent.indexOf(" Trident/");"rsrc-s"in t||r("rsrc-s",O);O=t["rsrc-s"];"rsrc-n"in t||r("rsrc-n",L);L=t["rsrc-n"];"rsrc-u"in t||r("rsrc-u",P);P=t["rsrc-u"];function ab(a){a=v(a);u(a,function(a){Va("img",a)})};function bb(a,b,c){Ia("js",a,b,c)}function cb(a){Qa("js",a)}function db(a,b){Pa("js",a,b)}function eb(a){a=v(a);u(a,function(a){Va("js",a)})}function fb(a,b,c){a=v(a);a=ga(a,function(a){return!!a});var d=[];u(a,function(a){void 0==K("js",a)&&d.push(a)});var e=!d.length;if(b){var f=fa(a,l(Sa,null,"js"));e&&f?b():(a=J("js",a.sort().join("|")),za(a,b))}c&&!e&&c(d)}function gb(a,b){a=v(a);u(a,function(a){if(a){var b=Q[a]||a,b=I("js",b),e=K("js",a);e&&b!=e&&hb(a)}});fb(a,b,ib)}
function ib(a){u(a,function(a){function c(){bb(e,a)}var d=R[a],e=Q[a]||a;d?gb(d,c):c()})}function hb(a){a=v(a);u(a,function(a){var c=[],d;for(d in R){var e=R[d],e=v(e);u(e,function(e){e==a&&c.push(d)})}u(c,function(a){hb(a)});cb(a)})}function jb(a,b){Ya("js",a,b)}function kb(a){$a("js",a)}var R={};"js-d"in t||r("js-d",R);var R=t["js-d"],Q={};"js-u"in t||r("js-u",Q);Q=t["js-u"];function lb(a,b,c){Ia("css",a,b,c)}function mb(a,b){Pa("css",a,b)}function nb(a){a=v(a);u(a,function(a){Va("css",a)})};function ob(a,b,c){if(b){var d=[],e;b=0;c&&(a+="\r\n");var f=a.indexOf("[\r\n",b);for(-1<f&&(b=f+3);-1<(f=a.indexOf(",\r\n",b));)e=pa(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e));f=a.indexOf("]\r\n",b);-1<f&&(e=pa(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e)));e="";a.length>b&&(e=a.substring(b),c&&oa(e,"\r\n")&&(e=e.substring(0,e.length-2)));return{k:d,a:e}}a=JSON.parse(a);"number"==typeof a.length?d=a:d=[a];return{k:d,a:""}}
function S(a,b,c,d,e){var f="process "+H(a),h=!w["experimental-process-async"],k;k=0;b.timing||(b.timing={});b.title&&(document.title=b.title);d&&b.url&&H(b.url)!=H(window.location.href)&&ua(b.url+window.location.hash,null,!1,!0);b.head&&(k=l(function(a,b){var c=T(a);pb(c);qb(c);E(f);rb(c,function(){b.spfProcessHead=n();F(f,h)})},null,b.head,b.timing),k=B(f,k));b.attr&&(k=l(function(a,b){for(var c in a){var d=document.getElementById(c);if(d){var e=a[c],f=void 0;for(f in e){var h=e[f];"class"==f?d.className=
h:"style"==f?d.style.cssText=h:d.setAttribute(f,h)}}}b.spfProcessAttr=n()},null,b.attr,b.timing),k=B(f,k));d=b.body||{};var g=k,p;for(p in d)k=l(function(a,b){var c=document.getElementById(a);if(c){var d=T(b),g=w["animation-class"];if(sb&&q(c,g)){E(f);var k=Fa(c);D(k,!0);g={r:d,reverse:!!e,f:null,h:null,g:c,G:g+"-old",H:g+"-new",w:e?g+"-reverse-start":g+"-forward-start",v:e?g+"-reverse-end":g+"-forward-end"};c=l(function(a){qb(a.r);da(a.g,a.w);a.f=document.createElement("div");a.f.className=a.G;var b=
a.g,c=a.f;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.h=document.createElement("div");a.h.className=a.H;a.h.innerHTML=a.r.j;a.reverse?(b=a.f,b.parentNode.insertBefore(a.h,b)):(b=a.f,b.parentNode.insertBefore(a.h,b.nextSibling))},null,g);B(k,c,0);c=l(function(a){ea(a.g,a.w);da(a.g,a.v)},null,g);B(k,c,0);c=l(function(a){a.g.removeChild(a.f);ea(a.g,a.v);ka(a.h);E(k);rb(a.r,function(){F(k)})},null,g);B(k,c,parseInt(w["animation-duration"],10));c=l(function(a,b){F(b)},null,g,f);
B(k,c);D(k)}else{qb(d);var p=function(){E(f);rb(d,function(){F(f,h)})};(g=w["experimental-html-handler"])?(E(f),g(d.j,c,function(){p();F(f,h)})):(c.innerHTML=d.j,p())}}},null,p,d[p],b.timing),k=B(f,k);p=k-g;b.foot?(k=l(function(a,b,c){c&&(b.spfProcessBody=n());a=T(a);qb(a);E(f);rb(a,function(){b.spfProcessFoot=n();F(f,h)})},null,b.foot,b.timing,p),k=B(f,k)):p&&(k=l(function(a){a.spfProcessBody=n()},null,b.timing),k=B(f,k));c&&(k=B(f,l(c,null,a,b)));D(f,h)}
function tb(a,b,c){var d="preprocess "+H(a),e;b.head&&(e=l(function(a){a=T(a);pb(a);ub(a);vb(a)},null,b.head),B(d,e));var f=b.body||{},h;for(h in f)f[h]&&(e=l(function(a,b){var c=T(b);ub(c);vb(c)},null,h,f[h]),B(d,e));b.foot&&(e=l(function(a){a=T(a);ub(a);vb(a)},null,b.foot),B(d,e));c&&B(d,l(c,null,a,b));D(d)}
function T(a){var b=new wb;if(!a)return b;if("[object String]"!=Object.prototype.toString.call(a))return a.scripts&&u(a.scripts,function(a){b.d.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&u(a.styles,function(a){b.c.push({url:a.url||"",text:a.text||"",name:a.name||""})}),a.links&&w["experimental-preconnect"]&&u(a.links,function(a){"spf-preconnect"==a.rel&&b.o.push({url:a.url||"",rel:a.rel||""})}),b.j=a.html||"",b;a=a.replace(xb,function(a,d,e,f){return"script"==
d?(a=(a=e.match(yb))?a[1]:"",d=(d=e.match(zb))?d[1]:"",e=Ab.test(e),b.d.push({url:d,text:f,name:a,async:e}),""):"style"==d?(a=(a=e.match(yb))?a[1]:"",b.c.push({url:"",text:f,name:a}),""):a});a=a.replace(Bb,function(a,d){var e=d.match(Cb),e=e?e[1]:"";if("stylesheet"==e){var e=(e=d.match(yb))?e[1]:"",f=d.match(Db),f=f?f[1]:"";b.c.push({url:f,text:"",name:e});return""}return"spf-preconnect"==e&&w["experimental-preconnect"]?(f=(f=d.match(Db))?f[1]:"",b.o.push({url:f,rel:e}),""):a});b.j=a;return b}
function rb(a,b){if(0>=a.d.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.d.length){var e=a.d[c],f=function(){};e.url?f=e.name?l(bb,null,e.url,e.name):l(db,null,e.url):e.text&&(f=e.name?l(jb,null,e.text,e.name):l(kb,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}function vb(a){0>=a.d.length||(a=ha(a.d,function(a){return a.url}),eb(a))}
function qb(a){if(!(0>=a.c.length))for(var b=0,c=a.c.length;b<c;b++){var d=a.c[b];d.url?d.name?lb(d.url,d.name):mb(d.url):d.text&&(d.name?Ya("css",d.text,d.name):$a("css",d.text))}}function ub(a){0>=a.c.length||(a=ha(a.c,function(a){return a.url}),nb(a))}function pb(a){0>=a.o.length||(a=ha(a.o,function(a){return"spf-preconnect"==a.rel?a.url:""}),ab(a))}function wb(){this.j="";this.d=[];this.c=[];this.o=[]}
var sb=function(){var a=document.createElement("div");if("transition"in a.style)return!0;for(var b=["webkit","Moz","Ms","O","Khtml"],c=0,d=b.length;c<d;c++)if(b[c]+"Transition"in a.style)return!0;return!1}(),Bb=/\x3clink([\s\S]*?)\x3e/ig,xb=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,Ab=/(?:\s|^)async(?:\s|=|$)/i,Db=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,yb=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,Cb=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,zb=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i;function Eb(a,b){var c=b||{};c.method=((c.method||"GET")+"").toUpperCase();c.type=c.type||"request";var d=a,e=w["url-identifier"]||"";if(e){var e=e.replace("__type__",c.type||""),f=x(d),d=f[0];0==e.lastIndexOf("?",0)&&-1!=d.indexOf("?")&&(e=e.replace("?","&"));d+=e+f[1]+f[2]}d=H(d);e={};e.spfUrl=d;e.startTime=n();e.fetchStart=e.startTime;n:{var h=Fb(a,c.current,null,c.type,!1),k=c.current,f=[];k&&(f.push(h+" previous "+k),f.push(h+" previous "+G(k).pathname));f.push(h);h=0;for(k=f.length;h<k;h++){var g;
r:{g=f[h];var p=z();if(g in p){p=p[g];if(sa(p)){ta(p);g=p.data;break r}qa(g)}g=void 0}if(g){f={key:f[h],response:g.response,type:g.type};break n}}f=null}e.spfPrefetched=!!f&&"prefetch"==f.type;e.spfCached=!!f;if(f)return setTimeout(l(Gb,null,a,c,e,f.key,f.response),0),null;f={};void 0!=c.u&&(f["X-SPF-Referer"]=c.u);c.current&&(f["X-SPF-Previous"]=c.current);if(h=w["advanced-header-identifier"])f["X-SPF-Request"]=h.replace("__type__",c.type),f.Accept="application/json";h={t:!1,a:"",complete:[]};e=
l(Hb,null,a,c,e,h);e={headers:f,D:w["request-timeout"],B:l(Ib,null,a,h),m:l(Jb,null,a,c,h),A:e,C:e};return"POST"==c.method?na("POST",d,c.q,e):na("GET",d,null,e)}function Gb(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=n();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,w["cache-unified"]||(qa(d),f=!0));if(b.b&&"multipart"==e.type){d=e.parts;for(var h=0;h<d.length;h++)b.b(a,d[h])}Kb(a,b,c,e,f)}
function Ib(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.t=-1!=a.toLowerCase().indexOf("multipart")}function Jb(a,b,c,d,e,f){if(c.t){e=c.a+e;var h;try{h=ob(e,!0,f)}catch(k){d.abort();b.e&&b.e(a,k);return}if(b.b)for(d=0;d<h.k.length;d++)b.b(a,h.k[d]);c.complete=c.complete.concat(h.k);c.a=h.a}}
function Hb(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var h in e.resourceTiming)c[h]=e.resourceTiming[h];else if(window.performance&&window.performance.timing){f=window.performance.timing.navigationStart;for(var k in e.resourceTiming)h=e.resourceTiming[k],void 0!==h&&(oa(k,"Start")||oa(k,"End")||"startTime"==k)&&(c[k]=f+Math.round(h))}"load"!=b.type&&(c.navigationStart=c.startTime);d.complete.length&&(d.a=pa(d.a),d.a&&Jb(a,b,d,e,"",!0));
var g;try{g=ob(e.responseText).k}catch(p){b.e&&b.e(a,p);return}if(b.b&&1<g.length)for(d=d.complete.length;d<g.length;d++)b.b(a,g[d]);if(1<g.length){var y;d=0;for(e=g.length;d<e;d++)k=g[d],k.cacheType&&(y=k.cacheType);g={parts:g,type:"multipart"};y&&(g.cacheType=y)}else g=1==g.length?g[0]:{};Kb(a,b,c,g,!0)}
function Kb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=Fb(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},h=parseInt(w["cache-lifetime"],10),k=parseInt(w["cache-max"],10);0>=h||0>=k||(k=z(),f={data:f,life:h,time:n(),count:0},ta(f),k[e]=f,setTimeout(ra,1E3))}d.timing=c;b.n&&b.n(a,d)}
function Fb(a,b,c,d,e){a=H(a);var f;w["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+G(b).pathname);return f||""};function Lb(a){return la(a,function(a){return q(a,w["link-class"])})}function Mb(a){return la(a,function(a){return q(a,w["nolink-class"])})}function Nb(a,b){return la(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function Ob(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=Lb(a.target);return!b||w["nolink-class"]&&Mb(a.target)?null:(a=Nb(a.target,b))?a.href:null}function Pb(a){return G(a).origin!=G(window.location.href).origin?!1:!0}
function Qb(){if(!t["nav-init"])return!1;var a=parseInt(t["nav-counter"],10)||0;a++;var b=parseInt(w["navigate-limit"],10),b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(t["nav-init-time"],10);a--;a=n()-a;b=parseInt(w["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}function Rb(a){if(!a.defaultPrevented){var b=Ob(a);b&&Pb(b)&&Qb()&&m("spfclick",{url:b,target:a.target})&&(Sb(b),a.preventDefault())}}function Tb(a){var b=Ob(a);b&&setTimeout(function(){Ub(b,void 0)},0)}
function Vb(a,b){var c=!(!b||!b["spf-back"]),d=b&&b["spf-referer"],e=b&&b["spf-current"],f=w["reload-identifier"];f&&(a=Ha(a,[f]));Pb(a)?Qb()?m("spfhistory",{url:a,referer:d,previous:e})&&Sb(a,null,e,d,!0,c):U(a,"1"):U(a,"9")}
function Sb(a,b,c,d,e,f){V();b=b||{};d=void 0==d?window.location.href:d;c=e?c:window.location.href;var h;n:{if(-1!=a.indexOf("#")&&(h=H(a),x(c||window.location.href)[0]==h)){h=!1;break n}h=!0}if(h)if(Wb(a,d,c,b)){r("nav-counter",(parseInt(t["nav-counter"],10)||0)+1);Xb(a);h=H(a);var k="preprocess "+H(h),g;for(g in C)k!=g&&0==g.lastIndexOf("preprocess",0)&&Da(g);g=Yb()[h];r("nav-request",g);r("nav-promote",null);r("nav-promote-time",null);g&&4!=g.readyState?(c=!!e,f="preprocess "+H(a),e="promote "+
H(a),r("nav-promote",a),r("nav-promote-time",n()),Da(f),D(e,!0),c||Zb(a,d,l(W,null,b))):(e=!!e,g=!!f,f=l(W,null,b),h=l($b,null,b,g),k=l(ac,null,b,g,""),w["advanced-navigate-persist-timing"]||bc(),b=Eb(a,{method:b.method,b:h,e:f,n:k,q:b.postData,type:"navigate"+(e?g?"-back":"-forward":""),current:c,u:d}),r("nav-request",b),e||Zb(a,d,f))}else U(a,"2");else cc(a),e||Zb(a,d,l(W,null,b))}function cc(a){a=x(a);a[1]&&(a[2]?(a=document.getElementById(a[2]))&&a.scrollIntoView():window.scroll(0,0))}
function Zb(a,b,c){try{b={"spf-referer":b},H(a,!0)==window.location.href?ua(a,null,!1,!0):va(!1,a,b,void 0)}catch(d){V(),c(a,d)}}function W(a,b,c){r("nav-request",null);dc(b,c,a)&&U(b,"10",c)}function $b(a,b,c,d){if(ec(c,d,a))if(d.reload)U(c,"5");else if(d.redirect)fc(a,d.redirect);else try{S(c,d,function(){gc(c,d,a)},!0,b)}catch(e){W(a,c,e)}else U(c,"3")}
function ac(a,b,c,d,e){r("nav-request",null);t["nav-promote"]==c&&(c=e.timing||{},c.navigationStart=t["nav-promote-time"],c.spfPrefetched=!0);c="multipart"==e.type;if(!c){if(!hc(d,e,a)){U(d,"4");return}if(e.reload){U(d,"5");return}if(e.redirect){fc(a,e.redirect);return}}try{S(d,c?{}:e,function(){cc(d);ic(d,e,a)},!0,b)}catch(f){W(a,d,f)}}function fc(a,b){try{b+=window.location.hash,ua(b,null,!0,!0)}catch(c){V(),W(a,b,c)}}function V(){var a=t["nav-request"];a&&(a.abort(),r("nav-request",null))}
function X(a,b){var c;a&&(c=Array.prototype.slice.call(arguments),c[0]=a,c=aa.apply(null,c));return!1!==c}
function U(a,b,c){c=c?c.message:"";V();Xb();var d=b;c&&(d+=" Message: "+c);m("spfreload",{url:a,reason:d});w["experimental-remove-history"]&&window.location.href==a&&(r("history-ignore-pop",!0),window.history.back());setTimeout(function(){var c=w["reload-identifier"];if(c){var d={};d[c]=encodeURIComponent(b);var c=a,h=x(c),c=h[0],k=-1!=c.indexOf("?")?"&":"?",g;for(g in d)c+=k+g,d[g]&&(c+="="+d[g]),k="&";a=c+h[1]+h[2]}window.location.href=a},0)}
function jc(a,b,c){b=b||{};c=c||a;Wb(a,void 0,void 0,b,!0)&&Eb(a,{method:b.method,b:l(kc,null,!1,b,c),e:l(lc,null,!1,b,c),n:l(mc,null,!1,b,c),q:b.postData,type:"load"})}function Ub(a,b,c){b=b||{};c=c||a;var d=window.location.href;Wb(a,void 0,void 0,b,!0)&&(b=Eb(a,{method:b.method,b:l(kc,null,!0,b,c),e:l(lc,null,!0,b,c),n:l(mc,null,!0,b,c),q:b.postData,type:"prefetch",current:d}),a=H(a),Yb()[a]=b)}function lc(a,b,c,d,e){a&&nc(d);a&&t["nav-promote"]==c?W(b,d,e):dc(d,e,b,!0)}
function kc(a,b,c,d,e){if(ec(d,e,b,!0)){if(e.reload){if(!a)return;if(t["nav-promote"]==c){U(d,"5");return}}if(e.redirect)oc(a,b,c,e.redirect);else{if(a){var f=l($b,null,b,!1,d,e),h="promote "+H(c);B(h,f);if(t["nav-promote"]==c){D(h,!0);return}}(a?tb:S)(d,e,function(){gc(d,e,b,!0)})}}}
function mc(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!hc(d,e,b,!0)){U(d,"4");return}if(e.reload){if(!a)return;if(t["nav-promote"]==c){U(d,"5");return}}if(e.redirect){oc(a,b,c,e.redirect);return}}var h="promote "+H(c);if(a){nc(d);if(t["nav-promote"]==c){B(h,l(ac,null,b,!1,c,d,e));D(h,!0);return}Da(h)}h=a?tb:S;try{h(d,f?{}:e,function(){ic(d,e,b,!0)})}catch(k){lc(a,b,c,d,k)}}
function oc(a,b,c,d){a=a?Ub:jc;var e={};u("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}function dc(a,b,c,d){a={url:a,err:b};(c=X((c||{}).onError,a))&&!d&&(c=m("spferror",a));return c}function Wb(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=X((d||{}).onRequest,a))&&!e&&(d=m("spfrequest",a));return d}function ec(a,b,c,d){a={url:a,part:b};(c=X((c||{}).onPartProcess,a))&&!d&&(c=m("spfpartprocess",a));return c}
function gc(a,b,c,d){a={url:a,part:b};X((c||{}).onPartDone,a)&&!d&&m("spfpartdone",a)}function hc(a,b,c,d){a={url:a,response:b};(c=X((c||{}).onProcess,a))&&!d&&(c=m("spfprocess",a));return c}function ic(a,b,c,d){a={url:a,response:b};X((c||{}).onDone,a)&&!d&&m("spfdone",a)}function nc(a){a=H(a);var b=Yb(),c=b[a];c&&c.abort();delete b[a]}function Xb(a){var b=Yb();a=a&&H(a);for(var c in b)a!=c&&nc(c)}
var bc,pc=window.performance&&(window.performance.clearResourceTimings||window.performance.webkitClearResourceTimings||window.performance.mozClearResourceTimings||window.performance.msClearResourceTimings||window.performance.oClearResourceTimings);bc=pc?l(pc,window.performance):ba;function Yb(){return"nav-prefetches"in t?t["nav-prefetches"]:r("nav-prefetches",{})};function Y(){Ua("js");Ua("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Y,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Y))}document.addEventListener?document.addEventListener("DOMContentLoaded",Y,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Y);Y();
var qc={init:function(a){var b=!("function"!=typeof window.history.pushState&&!xa().contentWindow.history.pushState);a=a||{};for(var c in ia)w[c]=c in a?a[c]:ia[c];for(c in a)c in ia||(w[c]=a[c]);if(b){c=dc;if(!t["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",ya,!1);r("history-init",!0);r("history-callback",Vb);r("history-error-callback",c);r("history-listener",ya);r("history-url",a);r("history-timestamp",n());var d={"spf-referer":document.referrer};
try{ua(a,d)}catch(e){c&&c(a,e)}}!t["nav-init"]&&document.addEventListener&&(document.addEventListener("click",Rb,!1),!w["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",Tb,!1),r("prefetch-listener",Tb)),r("nav-init",!0),r("nav-init-time",n()),r("nav-counter",0),r("nav-listener",Rb))}return b},dispose:function(){"undefined"!=typeof History&&History.prototype.pushState&&(V(),t["nav-init"]&&
(document.removeEventListener&&(document.removeEventListener("click",t["nav-listener"],!1),w["experimental-prefetch-mousedown"]&&document.removeEventListener("mousedown",t["prefetch-listener"],!1)),r("nav-init",!1),r("nav-init-time",null),r("nav-counter",null),r("nav-listener",null)),t["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",t["history-listener"],!1),r("history-init",!1),r("history-callback",null),r("history-error-callback",null),r("history-listener",null),
r("history-url",null),r("history-timestamp",0)));for(var a in w)delete w[a]},navigate:function(a,b){a&&(Pb(a)?Qb()?Sb(a,b):U(a,"1"):U(a,"9"))},load:function(a,b){jc(a,b)},prefetch:function(a,b){Ub(a,b)},process:function(a,b){function c(a,c,d,e){a==c&&b&&b(e)}var d=window.location.href;if("multipart"==a.type)for(var e=a.parts,f=0;f<e.length;f++){var h=l(c,null,f,e.length-1);S(d,e[f],h)}else h=l(c,null,0,0),S(d,a,h)}},rc={cache:{remove:qa,clear:function(){z({})}},script:{load:bb,get:db,ready:fb,done:function(a){Ma("js",
a,"");Na("js")},require:gb,declare:function(a,b){if(a){for(var c in a)R[c]=a[c];if(b)for(c in b)Q[c]=b[c]}},path:function(a){r("rsrc-p-js",a)},unload:cb,ignore:function(a,b){a=v(a);var c=J("js",a.sort().join("|"));Aa(c,b)},unrequire:hb,prefetch:eb},style:{load:lb,get:mb,unload:function(a){Qa("css",a)},path:function(a){r("rsrc-p-css",a)},prefetch:nb}},sc=this.spf=this.spf||{},tc;for(tc in qc)sc[tc]=qc[tc];for(var Z in rc)for(var uc in rc[Z])sc[Z]=sc[Z]||{},sc[Z][uc]=rc[Z][uc];m("spfready");})();
